const babelParser = require('@babel/eslint-parser')
const jest = require('eslint-plugin-jest')
const react = require('eslint-plugin-react')
const reactHooks = require('eslint-plugin-react-hooks')
const prettier = require('eslint-config-prettier/flat')
const globals = require('globals')

module.exports = [
  {
    ignores: [
      '**/lib/**',
      '**/stdlib/visitor.js',
      '**/val/**',
      '**/es/**',
      '**/dist/**',
      '**/logs/**',
      '**/npm/**',
      '**/*.bs.js',
      '**/*.bundle.js',
      '**/effector.browser.js',
      'scripts/browser/**',
      'tools/builder.js',
      'documentation/**',
      'examples/**',
      'packages/**',
      'recipes/**',
      'src/model-gen/**',
      'stats/**',
      // inputs of the babel plugin, not code meant to be linted
      'src/babel/__tests__/fixtures/**',
    ],
  },
  react.configs.flat.recommended,
  {
    files: ['**/*.{js,jsx,mjs,ts,tsx}'],
    languageOptions: {
      parser: babelParser,
      parserOptions: {
        requireConfigFile: false,
        babelOptions: {rootMode: 'upward'},
      },
      globals: {
        ...globals.node,
        ...globals.worker,
        ...globals.jest,
        ...globals.jasmine,
      },
    },
    plugins: {jest, react, 'react-hooks': reactHooks},
    settings: {react: {version: '19.0'}},
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react/react-in-jsx-scope': 'off',
      'react/no-children-prop': 'off',
      'react/prop-types': 'off',
      'react/display-name': 'off',
      'react/jsx-key': 'off',
      'react/no-unknown-property': 'off',
      'no-console': 'off',
      'no-cond-assign': 'warn',
      'no-unused-vars': 'warn',
      'prefer-template': 'off',
      'no-nested-ternary': 'off',
      'no-unneeded-ternary': 'warn',
      'no-underscore-dangle': 'off',
      'prefer-const': 'warn',
      'no-unused-labels': 'off',
      'no-extra-bind': 'error',
      'no-case-declarations': 'error',
      'no-useless-call': 'error',
      'prefer-arrow-callback': ['error', {allowNamedFunctions: true}],
      'object-shorthand': 'off',
      'arrow-body-style': ['error', 'as-needed'],
      'no-var': 'error',
      'no-duplicate-imports': 'off',
      'no-alert': 'error',
      'no-bitwise': 'off',
      'no-caller': 'error',
      'no-global-assign': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-proto': 'error',
      'no-iterator': 'error',
      'no-lone-blocks': 'off',
      'no-self-compare': 'error',
      'no-self-assign': ['error', {props: true}],
      'no-invalid-regexp': ['error', {allowConstructorFlags: ['u', 'y']}],
      'no-with': 'error',
      'no-new-func': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
    },
  },
  prettier,
]
