// flow-typed signature: 6a669bc214daeadda95cc2f43a8f7cc5
// flow-typed version: <<STUB>>/funland-laws_v0.1.5/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'funland-laws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'funland-laws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'funland-laws/dist/applicative' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/apply' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/chain-rec' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/chain' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/equiv' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/es5' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/functor' {
  declare module.exports: any;
}

declare module 'funland-laws/dist' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/monad' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/ord' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/semigroup' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/setoid' {
  declare module.exports: any;
}

declare module 'funland-laws/dist/umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'funland-laws/dist/applicative.js' {
  declare module.exports: $Exports<'funland-laws/dist/applicative'>;
}
declare module 'funland-laws/dist/apply.js' {
  declare module.exports: $Exports<'funland-laws/dist/apply'>;
}
declare module 'funland-laws/dist/chain-rec.js' {
  declare module.exports: $Exports<'funland-laws/dist/chain-rec'>;
}
declare module 'funland-laws/dist/chain.js' {
  declare module.exports: $Exports<'funland-laws/dist/chain'>;
}
declare module 'funland-laws/dist/equiv.js' {
  declare module.exports: $Exports<'funland-laws/dist/equiv'>;
}
declare module 'funland-laws/dist/es5.js' {
  declare module.exports: $Exports<'funland-laws/dist/es5'>;
}
declare module 'funland-laws/dist/functor.js' {
  declare module.exports: $Exports<'funland-laws/dist/functor'>;
}
declare module 'funland-laws/dist/index' {
  declare module.exports: $Exports<'funland-laws/dist'>;
}
declare module 'funland-laws/dist/index.js' {
  declare module.exports: $Exports<'funland-laws/dist'>;
}
declare module 'funland-laws/dist/monad.js' {
  declare module.exports: $Exports<'funland-laws/dist/monad'>;
}
declare module 'funland-laws/dist/ord.js' {
  declare module.exports: $Exports<'funland-laws/dist/ord'>;
}
declare module 'funland-laws/dist/semigroup.js' {
  declare module.exports: $Exports<'funland-laws/dist/semigroup'>;
}
declare module 'funland-laws/dist/setoid.js' {
  declare module.exports: $Exports<'funland-laws/dist/setoid'>;
}
declare module 'funland-laws/dist/umd.js' {
  declare module.exports: $Exports<'funland-laws/dist/umd'>;
}
