// flow-typed signature: bf4fcbd93c37371f0ef796d5d7a36066
// flow-typed version: <<STUB>>/funland_v0.1.5/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'funland'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'funland' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'funland/dist/applicative' {
  declare module.exports: any;
}

declare module 'funland/dist/apply' {
  declare module.exports: any;
}

declare module 'funland/dist/chain-rec' {
  declare module.exports: any;
}

declare module 'funland/dist/chain' {
  declare module.exports: any;
}

declare module 'funland/dist/es5' {
  declare module.exports: any;
}

declare module 'funland/dist/functor' {
  declare module.exports: any;
}

declare module 'funland/dist' {
  declare module.exports: any;
}

declare module 'funland/dist/kinds' {
  declare module.exports: any;
}

declare module 'funland/dist/monad' {
  declare module.exports: any;
}

declare module 'funland/dist/ord' {
  declare module.exports: any;
}

declare module 'funland/dist/semigroup' {
  declare module.exports: any;
}

declare module 'funland/dist/setoid' {
  declare module.exports: any;
}

declare module 'funland/dist/umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'funland/dist/applicative.js' {
  declare module.exports: $Exports<'funland/dist/applicative'>;
}
declare module 'funland/dist/apply.js' {
  declare module.exports: $Exports<'funland/dist/apply'>;
}
declare module 'funland/dist/chain-rec.js' {
  declare module.exports: $Exports<'funland/dist/chain-rec'>;
}
declare module 'funland/dist/chain.js' {
  declare module.exports: $Exports<'funland/dist/chain'>;
}
declare module 'funland/dist/es5.js' {
  declare module.exports: $Exports<'funland/dist/es5'>;
}
declare module 'funland/dist/functor.js' {
  declare module.exports: $Exports<'funland/dist/functor'>;
}
declare module 'funland/dist/index' {
  declare module.exports: $Exports<'funland/dist'>;
}
declare module 'funland/dist/index.js' {
  declare module.exports: $Exports<'funland/dist'>;
}
declare module 'funland/dist/kinds.js' {
  declare module.exports: $Exports<'funland/dist/kinds'>;
}
declare module 'funland/dist/monad.js' {
  declare module.exports: $Exports<'funland/dist/monad'>;
}
declare module 'funland/dist/ord.js' {
  declare module.exports: $Exports<'funland/dist/ord'>;
}
declare module 'funland/dist/semigroup.js' {
  declare module.exports: $Exports<'funland/dist/semigroup'>;
}
declare module 'funland/dist/setoid.js' {
  declare module.exports: $Exports<'funland/dist/setoid'>;
}
declare module 'funland/dist/umd.js' {
  declare module.exports: $Exports<'funland/dist/umd'>;
}
