// flow-typed signature: 33b0776eb330f99d3d7c7ed21e915169
// flow-typed version: <<STUB>>/jsverify_v0.8.4/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsverify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsverify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsverify/karma.jasmine.conf' {
  declare module.exports: any;
}

declare module 'jsverify/lib/api' {
  declare module.exports: any;
}

declare module 'jsverify/lib/arbitrary' {
  declare module.exports: any;
}

declare module 'jsverify/lib/arbitraryAssert' {
  declare module.exports: any;
}

declare module 'jsverify/lib/arbitraryBless' {
  declare module.exports: any;
}

declare module 'jsverify/lib/array' {
  declare module.exports: any;
}

declare module 'jsverify/lib/bless' {
  declare module.exports: any;
}

declare module 'jsverify/lib/dict' {
  declare module.exports: any;
}

declare module 'jsverify/lib/either' {
  declare module.exports: any;
}

declare module 'jsverify/lib/environment' {
  declare module.exports: any;
}

declare module 'jsverify/lib/finitemap' {
  declare module.exports: any;
}

declare module 'jsverify/lib/fn' {
  declare module.exports: any;
}

declare module 'jsverify/lib/functor' {
  declare module.exports: any;
}

declare module 'jsverify/lib/generator' {
  declare module.exports: any;
}

declare module 'jsverify/lib/json' {
  declare module.exports: any;
}

declare module 'jsverify/lib/jsverify' {
  declare module.exports: any;
}

declare module 'jsverify/lib/pair' {
  declare module.exports: any;
}

declare module 'jsverify/lib/primitive' {
  declare module.exports: any;
}

declare module 'jsverify/lib/random' {
  declare module.exports: any;
}

declare module 'jsverify/lib/record' {
  declare module.exports: any;
}

declare module 'jsverify/lib/recordWithEnv' {
  declare module.exports: any;
}

declare module 'jsverify/lib/show' {
  declare module.exports: any;
}

declare module 'jsverify/lib/shrink' {
  declare module.exports: any;
}

declare module 'jsverify/lib/small' {
  declare module.exports: any;
}

declare module 'jsverify/lib/string' {
  declare module.exports: any;
}

declare module 'jsverify/lib/suchthat' {
  declare module.exports: any;
}

declare module 'jsverify/lib/sum' {
  declare module.exports: any;
}

declare module 'jsverify/lib/typify' {
  declare module.exports: any;
}

declare module 'jsverify/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsverify/karma.jasmine.conf.js' {
  declare module.exports: $Exports<'jsverify/karma.jasmine.conf'>;
}
declare module 'jsverify/lib/api.js' {
  declare module.exports: $Exports<'jsverify/lib/api'>;
}
declare module 'jsverify/lib/arbitrary.js' {
  declare module.exports: $Exports<'jsverify/lib/arbitrary'>;
}
declare module 'jsverify/lib/arbitraryAssert.js' {
  declare module.exports: $Exports<'jsverify/lib/arbitraryAssert'>;
}
declare module 'jsverify/lib/arbitraryBless.js' {
  declare module.exports: $Exports<'jsverify/lib/arbitraryBless'>;
}
declare module 'jsverify/lib/array.js' {
  declare module.exports: $Exports<'jsverify/lib/array'>;
}
declare module 'jsverify/lib/bless.js' {
  declare module.exports: $Exports<'jsverify/lib/bless'>;
}
declare module 'jsverify/lib/dict.js' {
  declare module.exports: $Exports<'jsverify/lib/dict'>;
}
declare module 'jsverify/lib/either.js' {
  declare module.exports: $Exports<'jsverify/lib/either'>;
}
declare module 'jsverify/lib/environment.js' {
  declare module.exports: $Exports<'jsverify/lib/environment'>;
}
declare module 'jsverify/lib/finitemap.js' {
  declare module.exports: $Exports<'jsverify/lib/finitemap'>;
}
declare module 'jsverify/lib/fn.js' {
  declare module.exports: $Exports<'jsverify/lib/fn'>;
}
declare module 'jsverify/lib/functor.js' {
  declare module.exports: $Exports<'jsverify/lib/functor'>;
}
declare module 'jsverify/lib/generator.js' {
  declare module.exports: $Exports<'jsverify/lib/generator'>;
}
declare module 'jsverify/lib/json.js' {
  declare module.exports: $Exports<'jsverify/lib/json'>;
}
declare module 'jsverify/lib/jsverify.js' {
  declare module.exports: $Exports<'jsverify/lib/jsverify'>;
}
declare module 'jsverify/lib/pair.js' {
  declare module.exports: $Exports<'jsverify/lib/pair'>;
}
declare module 'jsverify/lib/primitive.js' {
  declare module.exports: $Exports<'jsverify/lib/primitive'>;
}
declare module 'jsverify/lib/random.js' {
  declare module.exports: $Exports<'jsverify/lib/random'>;
}
declare module 'jsverify/lib/record.js' {
  declare module.exports: $Exports<'jsverify/lib/record'>;
}
declare module 'jsverify/lib/recordWithEnv.js' {
  declare module.exports: $Exports<'jsverify/lib/recordWithEnv'>;
}
declare module 'jsverify/lib/show.js' {
  declare module.exports: $Exports<'jsverify/lib/show'>;
}
declare module 'jsverify/lib/shrink.js' {
  declare module.exports: $Exports<'jsverify/lib/shrink'>;
}
declare module 'jsverify/lib/small.js' {
  declare module.exports: $Exports<'jsverify/lib/small'>;
}
declare module 'jsverify/lib/string.js' {
  declare module.exports: $Exports<'jsverify/lib/string'>;
}
declare module 'jsverify/lib/suchthat.js' {
  declare module.exports: $Exports<'jsverify/lib/suchthat'>;
}
declare module 'jsverify/lib/sum.js' {
  declare module.exports: $Exports<'jsverify/lib/sum'>;
}
declare module 'jsverify/lib/typify.js' {
  declare module.exports: $Exports<'jsverify/lib/typify'>;
}
declare module 'jsverify/lib/utils.js' {
  declare module.exports: $Exports<'jsverify/lib/utils'>;
}
