// flow-typed signature: 55b1cb3bccbb5b4ce9e8318aae8d526e
// flow-typed version: <<STUB>>/linkifyjs_v2.1.8/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'linkifyjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'linkifyjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'linkifyjs/dist/linkify-element.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-element.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-element' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-element.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-html.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-html.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-html' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-html.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-jquery.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-jquery.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-jquery' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-jquery.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-hashtag.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-hashtag.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-hashtag' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-hashtag.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-mention.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-mention.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-mention' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-mention.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-ticket.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-ticket.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-ticket' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-plugin-ticket.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-polyfill' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-polyfill.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-react.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-react.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-react' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-react.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-string.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-string.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-string' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify-string.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify.amd' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify.amd.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify' {
  declare module.exports: any;
}

declare module 'linkifyjs/dist/linkify.min' {
  declare module.exports: any;
}

declare module 'linkifyjs/element' {
  declare module.exports: any;
}

declare module 'linkifyjs/html' {
  declare module.exports: any;
}

declare module 'linkifyjs/jquery' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify-element' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify-html' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify-jquery' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify-react' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify-string' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/parser' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/scanner' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/state' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/tokens' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/tokens/create-token-class' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/tokens/multi' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/core/tokens/text' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/plugins/hashtag' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/plugins/mention' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/plugins/ticket' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/utils/class' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/linkify/utils/options' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer/entity-parser' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer/evented-tokenizer' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer/html5-named-char-refs' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer/tokenize' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer/tokenizer' {
  declare module.exports: any;
}

declare module 'linkifyjs/lib/simple-html-tokenizer/utils' {
  declare module.exports: any;
}

declare module 'linkifyjs/plugins/hashtag' {
  declare module.exports: any;
}

declare module 'linkifyjs/plugins/mention' {
  declare module.exports: any;
}

declare module 'linkifyjs/plugins/ticket' {
  declare module.exports: any;
}

declare module 'linkifyjs/polyfill' {
  declare module.exports: any;
}

declare module 'linkifyjs/react' {
  declare module.exports: any;
}

declare module 'linkifyjs/string' {
  declare module.exports: any;
}

declare module 'linkifyjs/tasks/quick-es3' {
  declare module.exports: any;
}

declare module 'linkifyjs/tasks/rollup' {
  declare module.exports: any;
}

declare module 'linkifyjs/tasks/uglify' {
  declare module.exports: any;
}

declare module 'linkifyjs/tlds' {
  declare module.exports: any;
}

// Filename aliases
declare module 'linkifyjs/dist/linkify-element.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-element.amd'>;
}
declare module 'linkifyjs/dist/linkify-element.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-element.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-element.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-element'>;
}
declare module 'linkifyjs/dist/linkify-element.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-element.min'>;
}
declare module 'linkifyjs/dist/linkify-html.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-html.amd'>;
}
declare module 'linkifyjs/dist/linkify-html.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-html.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-html.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-html'>;
}
declare module 'linkifyjs/dist/linkify-html.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-html.min'>;
}
declare module 'linkifyjs/dist/linkify-jquery.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-jquery.amd'>;
}
declare module 'linkifyjs/dist/linkify-jquery.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-jquery.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-jquery.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-jquery'>;
}
declare module 'linkifyjs/dist/linkify-jquery.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-jquery.min'>;
}
declare module 'linkifyjs/dist/linkify-plugin-hashtag.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-hashtag.amd'>;
}
declare module 'linkifyjs/dist/linkify-plugin-hashtag.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-hashtag.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-plugin-hashtag.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-hashtag'>;
}
declare module 'linkifyjs/dist/linkify-plugin-hashtag.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-hashtag.min'>;
}
declare module 'linkifyjs/dist/linkify-plugin-mention.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-mention.amd'>;
}
declare module 'linkifyjs/dist/linkify-plugin-mention.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-mention.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-plugin-mention.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-mention'>;
}
declare module 'linkifyjs/dist/linkify-plugin-mention.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-mention.min'>;
}
declare module 'linkifyjs/dist/linkify-plugin-ticket.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-ticket.amd'>;
}
declare module 'linkifyjs/dist/linkify-plugin-ticket.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-ticket.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-plugin-ticket.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-ticket'>;
}
declare module 'linkifyjs/dist/linkify-plugin-ticket.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-plugin-ticket.min'>;
}
declare module 'linkifyjs/dist/linkify-polyfill.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-polyfill'>;
}
declare module 'linkifyjs/dist/linkify-polyfill.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-polyfill.min'>;
}
declare module 'linkifyjs/dist/linkify-react.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-react.amd'>;
}
declare module 'linkifyjs/dist/linkify-react.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-react.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-react.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-react'>;
}
declare module 'linkifyjs/dist/linkify-react.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-react.min'>;
}
declare module 'linkifyjs/dist/linkify-string.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-string.amd'>;
}
declare module 'linkifyjs/dist/linkify-string.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-string.amd.min'>;
}
declare module 'linkifyjs/dist/linkify-string.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-string'>;
}
declare module 'linkifyjs/dist/linkify-string.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify-string.min'>;
}
declare module 'linkifyjs/dist/linkify.amd.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify.amd'>;
}
declare module 'linkifyjs/dist/linkify.amd.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify.amd.min'>;
}
declare module 'linkifyjs/dist/linkify.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify'>;
}
declare module 'linkifyjs/dist/linkify.min.js' {
  declare module.exports: $Exports<'linkifyjs/dist/linkify.min'>;
}
declare module 'linkifyjs/element.js' {
  declare module.exports: $Exports<'linkifyjs/element'>;
}
declare module 'linkifyjs/html.js' {
  declare module.exports: $Exports<'linkifyjs/html'>;
}
declare module 'linkifyjs/index' {
  declare module.exports: $Exports<'linkifyjs'>;
}
declare module 'linkifyjs/index.js' {
  declare module.exports: $Exports<'linkifyjs'>;
}
declare module 'linkifyjs/jquery.js' {
  declare module.exports: $Exports<'linkifyjs/jquery'>;
}
declare module 'linkifyjs/lib/linkify-element.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify-element'>;
}
declare module 'linkifyjs/lib/linkify-html.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify-html'>;
}
declare module 'linkifyjs/lib/linkify-jquery.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify-jquery'>;
}
declare module 'linkifyjs/lib/linkify-react.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify-react'>;
}
declare module 'linkifyjs/lib/linkify-string.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify-string'>;
}
declare module 'linkifyjs/lib/linkify.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify'>;
}
declare module 'linkifyjs/lib/linkify/core/parser.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/parser'>;
}
declare module 'linkifyjs/lib/linkify/core/scanner.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/scanner'>;
}
declare module 'linkifyjs/lib/linkify/core/state.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/state'>;
}
declare module 'linkifyjs/lib/linkify/core/tokens.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/tokens'>;
}
declare module 'linkifyjs/lib/linkify/core/tokens/create-token-class.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/tokens/create-token-class'>;
}
declare module 'linkifyjs/lib/linkify/core/tokens/multi.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/tokens/multi'>;
}
declare module 'linkifyjs/lib/linkify/core/tokens/text.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/core/tokens/text'>;
}
declare module 'linkifyjs/lib/linkify/plugins/hashtag.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/plugins/hashtag'>;
}
declare module 'linkifyjs/lib/linkify/plugins/mention.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/plugins/mention'>;
}
declare module 'linkifyjs/lib/linkify/plugins/ticket.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/plugins/ticket'>;
}
declare module 'linkifyjs/lib/linkify/utils/class.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/utils/class'>;
}
declare module 'linkifyjs/lib/linkify/utils/options.js' {
  declare module.exports: $Exports<'linkifyjs/lib/linkify/utils/options'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/entity-parser.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer/entity-parser'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/evented-tokenizer.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer/evented-tokenizer'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/html5-named-char-refs.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer/html5-named-char-refs'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/index' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/index.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/tokenize.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer/tokenize'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/tokenizer.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer/tokenizer'>;
}
declare module 'linkifyjs/lib/simple-html-tokenizer/utils.js' {
  declare module.exports: $Exports<'linkifyjs/lib/simple-html-tokenizer/utils'>;
}
declare module 'linkifyjs/plugins/hashtag.js' {
  declare module.exports: $Exports<'linkifyjs/plugins/hashtag'>;
}
declare module 'linkifyjs/plugins/mention.js' {
  declare module.exports: $Exports<'linkifyjs/plugins/mention'>;
}
declare module 'linkifyjs/plugins/ticket.js' {
  declare module.exports: $Exports<'linkifyjs/plugins/ticket'>;
}
declare module 'linkifyjs/polyfill.js' {
  declare module.exports: $Exports<'linkifyjs/polyfill'>;
}
declare module 'linkifyjs/react.js' {
  declare module.exports: $Exports<'linkifyjs/react'>;
}
declare module 'linkifyjs/string.js' {
  declare module.exports: $Exports<'linkifyjs/string'>;
}
declare module 'linkifyjs/tasks/quick-es3.js' {
  declare module.exports: $Exports<'linkifyjs/tasks/quick-es3'>;
}
declare module 'linkifyjs/tasks/rollup.js' {
  declare module.exports: $Exports<'linkifyjs/tasks/rollup'>;
}
declare module 'linkifyjs/tasks/uglify.js' {
  declare module.exports: $Exports<'linkifyjs/tasks/uglify'>;
}
declare module 'linkifyjs/tlds.js' {
  declare module.exports: $Exports<'linkifyjs/tlds'>;
}
