// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


function set(param_0) {
  return /* Set */[param_0];
}

function init() {
  return 4;
}

function update(model, param) {
  if (typeof param === "number") {
    switch (param) {
      case 0 : 
          return model + 1 | 0;
      case 1 : 
          return model - 1 | 0;
      case 2 : 
          return 0;
      
    }
  } else {
    return param[0];
  }
}

var increment = /* Increment */0;

var decrement = /* Decrement */1;

var reset = /* Reset */2;

exports.increment = increment;
exports.decrement = decrement;
exports.reset = reset;
exports.set = set;
exports.init = init;
exports.update = update;
/* No side effect */
