// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY
//@flow
/* eslint-disable */

export const getPriority = (t: 'child' | 'pure' | 'barrier' | 'effect') => {
  switch(t) {
    case 'child': return 0
    case 'pure': return 1
    case 'barrier': return 2
    case 'effect': return 3
    default: return -1
  }
}