/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-fetch'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare var fet: typeof fetch;
declare var req: typeof Request;
declare var res: typeof Response;
declare var headers: typeof Headers;
declare module "cross-fetch" {
  declare export var fetch: typeof fet;
  declare export var Request: typeof req;
  declare export var Response: typeof res;
  declare export var Headers: typeof headers;
  declare export default typeof fetch;
}

