/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-adapter-react-16'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "enzyme-adapter-react-16" {
  import type { EnzymeAdapter } from "enzyme";

  declare class ReactSixteenAdapter mixins EnzymeAdapter {}

  declare module.exports: typeof ReactSixteenAdapter;
}

