/**
 * This is an autogenerated libdef stub for:
 *
 *   'fastify-favicon'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "fastify-favicon" {
  declare function defaultFaviconPlugin(): void;

  declare interface defaultFaviconPlugin$FastifyFaviconOptions {
    path?: string;
  }
  declare module.exports: typeof defaultFaviconPlugin;
}

