/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-enzyme'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module 'jest-enzyme' {
  declare interface jest$ToMatchElementOptions {
    ignoreProps?: boolean;
  }

  declare interface jest$Matchers<R> {
    toBeChecked(): void;
    toBeDisabled(): void;
    toBeEmptyRender(): void;
    toContainMatchingElement(selector: string): void;
    toContainMatchingElements(n: number, selector: string): void;
    toContainExactlyOneMatchingElement(selector: string): void;
    toContainReact(component: React.ReactElement<any>): void;
    toExist(): void;
    toHaveClassName(className: string): void;
    toHaveDisplayName(tagName: string): void;
    toHaveHTML(html: string): void;
    toHaveProp(
      propKey: {[key: string]: any, ...} | string,
      propValue?: any,
    ): void;
    toHaveRef(refName: string): void;
    toHaveState(
      stateKey: {[key: string]: any, ...} | string,
      stateValue?: any,
    ): void;
    toHaveStyle(
      styleKey: {[key: string]: any, ...} | string,
      styleValue?: any,
    ): void;
    toHaveTagName(tagName: string): void;
    toHaveText(text: string): void;
    toHaveValue(value: any): void;
    toIncludeText(text: string): void;
    toMatchElement(
      element: React.ReactElement<any>,
      options?: jest$ToMatchElementOptions,
    ): void;
    toMatchSelector(selector: string): void;
  }
}
