/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-hrtime'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "pretty-hrtime" {
  declare module.exports: typeof prettyHrtime;

  declare function prettyHrtime(
    hrTime: [number, number],
    options?: prettyHrtime$prettyHrtime$Options
  ): string;

  declare interface prettyHrtime$Options {
    verbose?: boolean;
    precise?: boolean;
  }
}

