/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "raf" {
  declare var raf: {
    (callback: (timestamp: number) => void): number,
    cancel: (handle: number) => void,
    polyfill: (globalObject?: any) => void
  };
  declare module.exports: typeof raf;
}

