/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-globals'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "rollup-plugin-node-globals" {
  import type { Plugin } from "rollup";

  declare export interface Options {
    include?: Array<string | RegExp> | string | RegExp | null;
    exclude?: Array<string | RegExp> | string | RegExp | null;
    sourceMap?: boolean;
    process?: boolean;
    global?: boolean;
    buffer?: boolean;
    dirname?: boolean;
    filename?: boolean;
    baseDir?: string;
  }
  declare export default function globals(options?: Options): Plugin;
}

