/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-builtins'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "rollup-plugin-node-builtins" {
  import type { Plugin } from "rollup";

  declare export interface Options {
    crypto?: boolean;
    fs?: boolean;
  }
  declare export default function builtins(options?: Options): Plugin;
}

