/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue'
 *
 * Fill this stub out by fixing all the errors.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module "vue" {
  import type { Vue } from "./vue";

  declare export default typeof Vue;

  declare export { CreateElement, VueConstructor } from "./vue";

  declare export {
    Component,
    AsyncComponent,
    ComponentOptions,
    FunctionalComponentOptions,
    RenderContext,
    PropOptions,
    ComputedOptions,
    WatchHandler,
    WatchOptions,
    WatchOptionsWithHandler,
    DirectiveFunction,
    DirectiveOptions
  } from "./options";

  declare export { PluginFunction, PluginObject } from "./plugin";

  declare export {
    VNodeChildren,
    VNodeChildrenArrayContents,
    VNode,
    VNodeComponentOptions,
    VNodeData,
    VNodeDirective
  } from "./vnode";
}

