name: forest browserstack tests

on:
  push:
    branches:
      - master
    paths:
      - 'src/forest/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node-20-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn build
        name: build libs
      - run: yarn test --runInBand
        name: dom tests
        env:
          DOM: 'true'
          BROWSERSTACK_USERNAME: ${{ secrets.browserstack_username }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.browserstack_access_key }}
